repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: debug-statements
      - id: name-tests-test
      - id: flake8
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        args: [--multi-line=3, --trailing-comma, --force-grid-wrap=0, --use-parentheses]


  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.1.0
    hooks:
      - id: python-use-type-annotations

  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.0.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/dfm/black_nbconvert
    rev: stable
    hooks:
    - id: black_nbconvert

  - repo: https://github.com/aflc/pre-commit-jupyter
    rev: v1.0.0
    hooks:
      - id: jupyter-notebook-cleanup
        args:
          - --remove-kernel-metadata
          - --pin-patterns
          - "[pin];[donotremove]"
